feat: создала запрос api для авторизации
encryption-machine/Front pull request #40
Opened 2023-07-10 14:26 UTC by Svetlana-2022

# запрос api для авторизации

2023-07-11 10:47 UTC, krekser37 commented on src/utils/Auth.js
> +function getResponseData(res) {
Если дальше ты создаешь функции через const, то я думаю, что здесь также надо.
Так же я бы использовала тернарный оператор:   return res.ok ? res.json() : Promise.reject(`Ошибка: ${res.status}`);

2023-07-11 10:48 UTC, krekser37 commented on src/utils/Auth.js
> +  export const authorize  = (email, password) => {
Нас учили называть функции более понятно: postApiAutorisation

2023-07-11 10:51 UTC, krekser37 commented on src/utils/Auth.js
> +      }).then(getResponseData);
Если функция в 4 строчке получает res, то наверное он должен как-то передаваться ей, возможно так: .then(res=>getResponseData(res)).

2023-07-11 10:54 UTC, krekser37 commented on src/utils/Auth.js
> +        headers: {'Content-Type': 'application/json'},
Писали, что у нас должно быть предупреждение про куки. Если оно будет, тогда здесь должно быть:       headers: {
        "Content-Type": "application/json;charset=utf-8",
        Authorization: 'Bearer ' + getCookie('token'),
      },

2023-07-11 10:55 UTC, krekser37 commented on src/utils/Auth.js
> +        body: JSON.stringify({ email, password })
Такой запрос проходит? Вроде у Маши похожее не проходило, так нужно показывать в какой ключ передается нужный объект. Таким способом:   body: JSON.stringify({ email: email, password: password}),

2023-07-11 11:05 UTC, krekser37 commented on src/utils/Auth.js
> +  export const authorizeVerify = (token) => {
Не нашла, где эта функция используется?

2023-07-11 11:14 UTC, krekser37 requested changes
Света, посмотри, пожалуйста, комментарии.

2023-07-11 15:23 UTC, Svetlana-2022 commented on src/utils/Auth.js
> +        body: JSON.stringify({ email, password })
У меня прошел, могу поправить

2023-07-12 07:57 UTC, krekser37 commented on src/utils/Auth.js
> +        body: JSON.stringify({ email, password })
Отлично, тогда так оставляй)

2023-07-13 10:50 UTC, MariaGrom commented
1. при успешной авторизации  пользователя попап формы авторизации так и остается открытым и значение "Войти" в хэдэре не меняется на "Выйти"
2. когда приходит ошибка с бэка (например человек ошибся при вводе почты при авторизации), то эту ошибку пользователь не видит - в форму ничего не падает. просто не проходит авторизация без объяснения причины

2023-07-13 10:52 UTC, MariaGrom requested changes
1. при успешной авторизации пользователя попап формы авторизации так и остаются принятыми и значением "Войти" в хэдэре не меняется на "Выйти"
2. когда приходит ошибка с возвратом (например, человек ошибается при вводе почты при авторизации), то эта ошибка пользователя не видится - в формуле ничего не падает. просто не проходит авторизация без объяснения причин

2023-07-19 10:20 UTC, MariaGrom approved these changes

2023-07-19 10:20 UTC, MariaGrom commented on src/components/SignInForm/SignInForm.jsx
> +  console.log(errorText, 'errorText');
перед слиянием этот лог лучше удалить, а то он всю консоль засоряет

2023-07-19 10:56 UTC, teplostanski approved these changes

2023-07-19 11:18 UTC, merged