Fix/header
encryption-machine/Front pull request #44
Opened 2023-07-14 08:47 UTC by MariaGrom

Создала отдельный компонент под ссылки.
Пофиксила шапку  - внесла компонента Ссылку.

2023-07-15 15:16 UTC, teplostanski approved these changes

2023-07-15 22:58 UTC, teplostanski requested changes
Пожалуйста не используй селекторы в стилях, а если уж так хочется то используй селектой как дочерний к классу, например 
```scss
.class {
  ...какой-то код
  & > selector {
    ...какой-то код
  }
}
```

Стили из хедера перебивают мои стили

2023-07-17 08:42 UTC, MariaGrom commented
удалила селекторы из стилей. Проверь теперь у себя - перебиваются ли стили или нет?

2023-07-17 20:36 UTC, teplostanski approved these changes

2023-07-17 20:39 UTC, merged